userdatafile = 'userdata.toml'
psprofilefile = 'C:\Users\User\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1'
stopfile = 'C:\TEMP\psolympics-stop.txt'
hintfile = 'C:\TEMP\psolympics-hint.txt'
skipfile = 'C:\TEMP\psolympics-skip.txt'
transcriptfile = 'C:\TEMP\psolympics-transcript.txt'
# This needs to be an absolute path for Windows Terminal profile use
tpane = 'Z:\sec504windowslabfiles\psolympics\tpane.exe'

[[events]]

name = 'Getting Started with PowerShell'
path = 'Z:\sec504windowslabfiles\psolympics\psolympics-gettingstarted.toml'

[[events]]

name = 'Working with the Pipeline'
path = 'Z:\sec504windowslabfiles\psolympics\psolympics-pipelines.toml'

[[events]]

name = 'Navigating PowerShell Drives'
path = 'Z:\sec504windowslabfiles\psolympics\psolympics-drives.toml'

[[events]]

name = 'Working with PowerShell Variables'
path = 'Z:\sec504windowslabfiles\psolympics\psolympics-variables.toml'


