"Navigating the File System" = 94
"Navigating the PowerShell Drives" = 427
"Getting Started with PowerShell" = 36
"Working with the Pipeline" = 45
"Test Event" = 30
"Navigating PowerShell Drives" = 506
"Working with PowerShell Variables" = 105
